[package]
name = "bohelper"
version = "0.1.0"
authors = ["Andrzej Grzeslak <agrzeslak0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
x86asm = "0.1.0"
